version: "3"

services:
  # --- Application Infrastructure --- #
  server: # Express Server
    build: ./server
    environment:
      - DATABASE_HOST=postgres
    ports:
      - "3131:3131"

  # --- Backend Infrastructure --- #
  nginx: # Nginx
    image: nginx
    links:
      - server:server
    ports:
      - "80:80"
  postgres: # PostgreSQL
    image: postgres:12.2
    hostname: postgres
    env_file: .env
    ports:
      - 5432:5432
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=${DATABASE_USER:-infura}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-infura}
      - POSTGRES_DB=test
  pgadmin: # Postgres Dashboard
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-infura}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-infura}
      # PGADMIN_ENABLE_TLS: 1
    ports:
      - "${PGADMIN_PORT:-5050}:80"
      # TLS
      # - "${PGADMIN_PORT:-5443}:8443"
